tools:
  ffmpeg: "C:/SVN/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe"
  colmap: "C:/SVN/noCudaColmap/COLMAP.bat"
  openmvs_interface: "C:/SVN/vc17/x64/Release/InterfaceCOLMAP.exe"
  openmvs_densify: "C:/SVN/vc17/x64/Release/DensifyPointCloud.exe"
  openmvs_reconstruct: "C:/SVN/vc17/x64/Release/ReconstructMesh.exe"
  openmvs_refine: "C:/SVN/vc17/x64/Release/RefineMesh.exe"
  openmvs_texture: "C:/SVN/vc17/x64/Release/TextureMesh.exe"