tools:
  ffmpeg: "C:/SVN/Project/src/main/resources/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe"
  colmap: "C:/SVN/Project/src/main/resources/colmap-x64-windows-cuda/COLMAP.bat"
  openmvs_interface: "C:/SVN/Project/src/main/resources/x64/Release/InterfaceCOLMAP.exe"
  openmvs_densify: "C:/SVN/Project/src/main/resources/x64/Release/DensifyPointCloud.exe"
  openmvs_reconstruct: "C:/SVN/Project/src/main/resources/x64/Release/ReconstructMesh.exe"
  openmvs_refine: "C:/SVN/Project/src/main/resources/x64/Release/RefineMesh.exe"
  openmvs_texture: "C:/SVN/Project/src/main/resources/x64/Release/TextureMesh.exe"